### ISSUE TITLE
This code does not work

### ISSUE THREAD

**Issue by curlywallst** [learn-co-curriculum/redux-create-store#10]
I copied and pasted the code and get the error that within render() store is not defined.

**Comment by sdklos** [comment]
I also had problems with this code -  in the render function "container.textContent = store.getState.count" threw an error until I changed it to "container.textContent = store.getState().count"

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
