### ISSUE TITLE
render() needs to be fixed.

### ISSUE THREAD

**Issue by LS-C** [learn-co-curriculum/redux-create-store#11]
state isn't accessible with the example render function below.
function render() {
  let container = document.getElementById('container');
  container.textContent = store.getState.count;
};

instead I had to invoke store.getState function first then access .count to render current state to DOM.

Thank you!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
