### ISSUE TITLE
The errors in this lab really should be fixed

### ISSUE THREAD

**Issue by bmolina-nyc** [learn-co-curriculum/redux-create-store#12]
there seems to be some errors here and apparently the lab hasn't been updated even though problems have been noted since at least September. Below might not be the perfect solution but this is how I get the lab to actually run.

Line 13:   dispatch({type: '@@INIT'})   leaving this here throws a store not defined error - the store is created on Line 37 so calling this for the first time within createStore seems to throw an error that I think is calling dispatch on a store that hasn't initialized yet.

To fix this error i called store.dispatch({type: '@@INIT'}) outside of the createStore function, directly on line 38 (after the store = createStore function) This allows for the DOM to show a state of zero on a page reload.

But for the DOM to display at all we need to fix the Render function. It doesn't render anything because you need to call the function on line 34  - it should be store.getState() which would give you {count: number}...so store.getState().count gives you the number for the DOM

function createStore(reducer) {
  let state;

  function dispatch(action) {
    state = reducer(state, action);
    render();
  }

  function getState() {
    return state;
  };

  return {
    dispatch,
    getState
  };
};

function changeCount(state = { count: 0 }, action) {
  switch (action.type) {
    case 'INCREASE_COUNT':
      return { count: state.count + 1 };

    default:
      return state;
  }
}

function render() {
  let container = document.getElementById('container');
  container.textContent = store.getState().count;
};

let store = createStore(changeCount) // createStore takes the changeCount reducer as an argument
store.dispatch({type: '@@INIT'})

let button = document.getElementById('button');

button.addEventListener('click', function() {
  store.dispatch({ type: 'INCREASE_COUNT' });
});

**Comment by gb23** [comment]
Flatiron team, I would really like to see a working solution with `store.dispatch({type: '@@init'})` kept inside of our new function because the main focus of this lesson is to "move code common to every javascript application inside our new function" .  The lesson shows this approach, but the code does not work.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
