### ISSUE TITLE
the code is not working

### ISSUE THREAD

**Issue by Raskovan** [learn-co-curriculum/redux-create-store#13]
I was following alone and the final code is giving an error:
ReferenceError: store is not defined
    at render (reducer_old.js:34)
    at dispatch (reducer_old.js:6)
    at createStore (reducer_old.js:13)
    at reducer_old.js:37 

Please fix.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
