### ISSUE TITLE
Code still doesn't work

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/redux-create-store#14]
The solution code passes the test but doesn't work in the browser. When I paste in the solution code and run `open index.html`, the console presents me with this error `Uncaught SyntaxError: Unexpected identifier`. Please provide a better lab.

**Comment by maxwellbenton** [comment]
Hi @JoeQuattrone,

Thank you for providing this feedback. We've updated and tested this lesson's code snippets and confirmed they now lead to a working example and have also added a solution branch from those that will work in browser, which should resolve this issue.

We apologize for any frustration this lab may have caused you, but we appreciate you taking the time to provide feedback!

Thank you!
